
[server]
	#Login Timeout(s)
	#Range: 0 ~ 1200
	secs = 60
	#Commands in whitelist can be executed before player login.
	commandNames = []
	#Available storage method: file(json file) / capability(save in player nbt)
	storageMethod = "file"
	#Default game type switched after player login
	#Range: 0 ~ 3
	defaultGameType = 0
	#Protect player's coordinates
	protectPlayerCoord = false

